### ISSUE TITLE
Constant flickering 

### ISSUE THREAD

**Issue by Zanark** [PrayagS/polybar-spotify#1]
Good Afternoon @PrayagS 

I loved your polybar module however I'm having a small issue. I do not know much about bash scripting yet therefore I would like to consult you for some help regarding this issue.

The player keeps flickering and this message appears when I pause the player

`polybar-msg: No channel available for pid`

I tried editing the bash script but still got no idea whats causing the issue.

P.S. Can you please share the fonts you are using for polybar, I was unable to display the prev and next icons on mine.

**Comment by PrayagS** [comment]
https://github.com/PrayagS/polybar-spotify/blob/8c0881fc92fe586f05fd9ff741b7ffb015175ce8/get_spotify_status.sh#L6

The line showed above is one of the two lines in the script that control the play-pause icons. What I need you to verify is that,

- In place of `now-playing`, you have the correct name of the bar which contains the module and also whether IPC has been enabled for that particular bar or not.
- In place of `spotify-play-pause`, you have the correct name of the module which shows the play-pause icon.

And as far as the fonts are concerned, just use a [Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts) variant of your favorite font. The icons will render fine if you use those fonts.

**Comment by Zanark** [comment]
@PrayagS thanks, it indeed was `now-playing` instead of my polybar's name.

Yes I'm using a Nerd font, but it still doesn't work, will look into the issue.
Thanx a ton for replying so soon :smile:

**Comment by PrayagS** [comment]
Just make sure to update your font cache after you installed the new font by running `fc-cache -rf`.

And check whether what you're writing in the polybar config as the font name matches with the font you want. So for example, if you wrote `JetBrainsMono Nerd Font` in your polybar config, run `fc-match "JetBrainsMono Nerd Font"` and verify whether the string is matching with the exact font you want.

I'm closing the issue for now but let me know if you are still facing problems.
