### ISSUE TITLE
Is the module supposed to be pulsating? 

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [PrayagS/polybar-spotify#14]
The title part of the module displaces the modules beside it slightly (eq: previous, play-pause, next) when it starts scrolling the text. It's static when paused. 

https://streamable.com/kap4mz

**Comment by thalestas** [comment]
Same here. I tried make the text width fixed using polybar tokens but without success.

**Comment by PrayagS** [comment]
I currently use a different bar with a fixed width and only the spotify module at the center of it. Hence, whenever it is scrolling, it just takes up the whole space available and I don't see it pulsating.

Let me try out your kind of setup. I do see it pulsating a little on the demo GIF where I was using a full bar like you.

@thalestas Can you please share with us what you tried?

**Comment by PrayagS** [comment]
@1-minute-to-midnight I tried expanding my bar and here is the result:
![](https://i.imgur.com/cFj84um.gif)

I just increased the `width` property for that particular bar to try to simulate your situation. Also, note that I placed all the spotify modules in `modules-center`, The `modules-left` and `modules-right` sections have no modules in them.

**Comment by 1-minute-to-midnight** [comment]
Could you clarify please? I didn't understand. My bar width is at 100% and all my spotify modules are at the center. Here is my config file for polybar: https://gitlab.com/1minutetomidnight/dotfiles/-/blob/master/.config/polybar/config

**Comment by PrayagS** [comment]
@1-minute-to-midnight I see the issue now. Are you using a monospaced font for that label? I can only reproduce the pulsating when some other non-monospaced font is used (eg. Japanese font when a song with a Japanese title comes up). Demo:
![](https://i.imgur.com/lbsFh3Z.gif)

Switch to a regular monospaced font and check if you can still reproduce the issue.

**Comment by PrayagS** [comment]
This issue on Polybar might help. polybar/polybar#490

**Comment by 1-minute-to-midnight** [comment]
I was using Meslo Nerd Font. I switched to Meslo Nerd Font Mono and still no change.

**Comment by PrayagS** [comment]
@1-minute-to-midnight Strange. I currently use TerminessTTF Nerd Font (not the mono version). Maybe try with a bunch of monospaced fonts.

**Comment by PrayagS** [comment]
Also, I'm assuming that you use the same kind of monospaced font for icons as well.

**Comment by 1-minute-to-midnight** [comment]
Yes, I use the same for icons as well. I'll try with the Terminess Font

**Comment by 1-minute-to-midnight** [comment]
Finally got it with Meslo Nerd Font Mono itself. The font hadn't taken effect before. Now it doesn't displace the surrounding modules. Thanks for all your help :)
