### ISSUE TITLE
Polybar-Spotify will control playback of other apps when Spotify is closed

### ISSUE THREAD

**Issue by OBITORASU** [PrayagS/polybar-spotify#19]
I was playing around with the scripts and my polybar config when I noticed that the playback modules tend to control the playback of my firefox media when I have spotify closed. This behavior seems unexpected since the playback is only supposed to control the playback of spotify media if and only if spotify is open. The solution is pretty simple, using `--player=spotify` instead of just `spotify` for all the `playerctl` commands gives the expected results. I think the commands should be updated in the `polybar config` section of the readme. Do let me know your views.

**Comment by PrayagS** [comment]
@OBITORASU Hey thanks for pointing this out. Maybe there are some upstream changes in `playerctl` that have changed the behavior.

I've merged the PR from @amirhossein-ka which adds the change in the `polybar` config.
