### ISSUE TITLE
Is there a way to fix the pulsating with japanese fonts?

### ISSUE THREAD

**Issue by myang7** [PrayagS/polybar-spotify#22]
I'm using Noto Sans CJK JP Light:style=Light,Regular for the jp font in the polybar config.
It's the same pulsating as described in #14

**Comment by PrayagS** [comment]
Is that a monospaced font? There's this font called Sarasa which has a monospaced variant for CJK characters. There's also Source Han Sans which supports Chinese characters.

I personally use Sarasa and I see no pulsating with at least the Japanese characters.

If you read through #14, you'll see that is the exact solution. Using proper monospace fonts fixes this issue. Let me know if it works for you. If not, feel free to get back here.

**Comment by myang7** [comment]
Yeah I fixed it by using the mono version of noto sans jp I forgot to close this after I fixed it sorry.

**Comment by mdoliv** [comment]
I'm facing this same issue with Japanese fonts, I've tried a collection of fonts for both the icons and the Japanese characters, which include:

### Icons + Latin text
- JetBrainsMono Nerd Font (both regular and "Mono" suffixed, i.e. "JetBrainsMono Nerd Font Mono");
- Hack Nerd Font (same as above);
- Sarasa Mono (testing a non-Nerd Font monospaced font, where I replaced icons for regular ASCII characters);

### Japanese characters
- Noto Sans Mono CJK;
- Source Han Sans;
- Sarasa Mono J;

Got no luck with any of those combinations, the bar is still pulsating in the transition between Japanese and Latin characters.

**Comment by PrayagS** [comment]
@flayner2 At this point, I think you'd have better luck discussing this over at polybar's GitHub rather than here.
