### ISSUE TITLE
Play/Pause button doesn't update the icon

### ISSUE THREAD

**Issue by p0ryae** [PrayagS/polybar-spotify#26]
I have `enable-ipc = true` in my bar config - I expect the play button turn into the opposite when I'm clicking but it doesn't. It's always on 1 specific icon no matter what

**Comment by PrayagS** [comment]
Can you please post your scripts and polybar config?

https://github.com/PrayagS/polybar-spotify/blob/f8f492bc5619e661ef4cf90223887c2f19d8d5b7/get_spotify_status.sh#L4-L5

These are the lines in the script where you need to mention the name of the bar containing the modules. So make sure that the correct name is present in the script.

The script then fetches the PID of that bar and calls`update_hooks` to update the icons. You can also try to echo this and verify whether the correct PID is being fetched.

**Comment by p0ryae** [comment]
![image](https://user-images.githubusercontent.com/59381835/159183080-89e953ac-ac0f-4bc6-8d1a-cf0aaa20faa4.png)

And when I run it in terminal:
![image](https://user-images.githubusercontent.com/59381835/159183250-3a48ae35-b881-400c-b340-4a6e7c6cc3e2.png)

Pretty sure its catching it.

**My polybar config:** https://sourceb.in/n0WPjmomMC

**Comment by PrayagS** [comment]
Can you also try to call the `update_hooks` externally with the PID you showed?

https://github.com/PrayagS/polybar-spotify/blob/f8f492bc5619e661ef4cf90223887c2f19d8d5b7/get_spotify_status.sh#L19-L25

Just source this function and then try running the following in your shell.
```sh
update_hooks <pid> 1
update_hooks <pid> 2
```
