### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by NetMan134** [PrayagS/polybar-spotify#27]
Hello!
I stumbled upon this little project and gladly want to use it, but I haven't seen a LICENSE for it anywhere, it is stated, that without it - no one can use such a code, or distribute it, etc. I recommend checking out https://choosealicense.com to see available licenses, see what they do and which one do you prefer.

And primarily for these use cases I'd recommend these licences:

MIT - https://choosealicense.com/licenses/mit/
WTFPL - https://choosealicense.com/licenses/wtfpl
GNU GPL v3 - https://choosealicense.com/licenses/gpl-3.0/

Thanks,
Oskar

**Comment by PrayagS** [comment]
I appreciate you taking the time to raise this concern. Adding a license right away :)
