### ISSUE TITLE
Any way to hide the bars between each module

### ISSUE THREAD

**Issue by Igo-Cigo** [PrayagS/polybar-spotify#28]
only for the spotify modules not for other modules

**Comment by PrayagS** [comment]
Can you please elaborate?

By hiding the module, do you mean that it should be hidden when no music is playing? If yes, I had looked into that before and unfortunately, polybar requires fixed-sized modules so it'll always occupy the same space.

I suggest you also check out polybar's GitHub issues and r/polybar in case this has been discussed before.

**Comment by Igo-Cigo** [comment]
Issue with polybar sorry
