### ISSUE TITLE
Cant get the script to work

### ISSUE THREAD

**Issue by Morantoine** [PrayagS/polybar-spotify#4]
Hey, the script returns cute_child in the bar. However, zscroll works fine in terminal. The play pause button also does not appear, the only thing that works is the next/previous song. Any help?

**Comment by PrayagS** [comment]
Please post your scripts and relevant parts from the polybar config.

**Comment by KivalM** [comment]
Hi. getting the same error as above.

**Modules**

[module/prev]
type = custom/script
exec = echo "玲"
format-background = ${color.shade3}
format-foreground = ${color.modulefg}
format = <label>
click-left = playerctl previous spotify

[module/pause]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo "契"
format-background = ${color.shade3}
format-foreground = ${color.modulefg}
initial = 1
click-left = playerctl play-pause spotify

[module/next]
type = custom/script
exec = echo "怜"
format-background = ${color.shade3}
format-foreground = ${color.modulefg}
format = <label>
click-left = playerctl next spotify

[module/spotify]
type = custom/script
tail = true
format-prefix = "  "
format = <label>
format-background = ${color.shade3}
format-foreground = ${color.modulefg}
exec = ~/.config/polybar/scroll_spotify_status.sh



**Relevant Config**

enable-ipc = true
modules-left = powermenu spotify prev pause next 
modules-center = workspaces
modules-right = 

And it provides this output

![2020-10-05_141430-171x18_scrot](https://user-images.githubusercontent.com/65903718/95078268-26b47380-0715-11eb-97f6-65b717289d25.png)

Running the script in terminal provides this output

~/.config/polybar ❯ ./get_spotify_status.sh 
polybar-msg: No channel available for pid 
Night Train - Code Elektro

**Comment by J0eKing** [comment]
I did some testing. It seems pgrep doesnt detect polybars based on their bar name. Top will list 2 processes names "polybar". So if you have 2 bars it wont be able to transmit messages to the correct one.

**Comment by KivalM** [comment]
I did some research. It seems it wont correctly detect the pid if the command you used was not just "polybar barname". For example i used "polybar -c PATH mainbar". So it wont be detected by "pgrep -f "polybar mainbar"

I edited the script to add it. It fixed the "polybar-msg: No channel available for pid" error. However cute_child still appears.

**Comment by PrayagS** [comment]
@J0eKing Can you post your scripts as well?

**Comment by KivalM** [comment]
```
#!/bin/bash

if [ "$(playerctl --player=playerctld status)" = "Stopped" ]; then
    echo "No music is playing"
elif [ "$(playerctl --player=playerctld status)" = "Paused"  ]; then
    polybar-msg -p "$(pgrep -f "polybar -c /home/joe/.config/polybar/config-1 bottommain")" hook pause 1 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
else # Can be configured to output differently when player is paused
    polybar-msg -p "$(pgrep -f "polybar -c /home/joe/.config/polybar/config-1 bottommain")" hook pause 0 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
fi
```

the other script wasn't edited

**Comment by KivalM** [comment]
Another issue i noticed which may or may not be related 
When i run 
`playerctl --player=playerctld status`
when there is no music playing
it returns
`No player could handle this command`
instead of 
`Stopped` as indicated in the script

**Comment by PrayagS** [comment]
Can you please try using my version of scripts? I had modified them to also work around the other issue that you mentioned (when no music player is running).

- `get_playerctl_status.sh`
```sh
#!/bin/bash

STATUS=$(playerctl --player=playerctld status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo $STATUS
else
    echo "No player is running"
fi
```

- `get_spotify_status.sh`
```sh
#!/bin/bash

STATUS=$($HOME/.config/polybar/scripts/get_playerctl_status.sh)

if [ "$STATUS" = "Stopped" ]; then
    echo "No music is playing"
elif [ "$STATUS" = "Paused"  ]; then
    polybar-msg -p "$(pgrep -f "polybar -c /home/joe/.config/polybar/config-1 bottommain")" hook pause 2 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
elif [ "$STATUS" = "No player is running"  ]; then
    echo $STATUS
else
    polybar-msg -p "$(pgrep -f "polybar -c /home/joe/.config/polybar/config-1 bottommain")" hook pause 1 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
fi
```
**Make sure to add the correct location of** `get_playerctl_status.sh`.

I modified the script to include your `pgrep` change and correct module name. However, instead of `hook pause 0` and `hook pause 1`, I've changed it to `hook pause 1` and `hook pause 2`. This is because afaik while accessing the hooks from outside, they're supposed to be 1-indexed.

- `scroll_spotify_status.sh`
```sh
#!/bin/bash

# see man zscroll for documentation of the following parameters
zscroll -l 30 \
        --delay 0.1 \
        --scroll-padding "  " \
        --match-command "$HOME/.config/polybar/scripts/get_playerctl_status.sh" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true '/home/prayag_s/.config/polybar/scripts/get_spotify_status.sh' &

wait
```
**Make sure to add the correct location of** `get_playerctl_status.sh` **and** `get_spotify_status.sh`.

**Comment by KivalM** [comment]
Alright so i tried out your changes and i got it to work
Works great ^^

![2020-10-06_143011-265x25_scrot](https://user-images.githubusercontent.com/65903718/95201942-e9b5b300-07e0-11eb-8e7a-19e836f235c8.png)

**Comment by Morantxu** [comment]
Hey, back here, sorry for the delay. I still dont get it to work, still showing cute_child : here are my scripts

get_spotify_status.sh : 

`#!/bin/bash

if [ "$(playerctl --player=playerctld status)" = "Stopped" ]; then
    echo "No music is playing"
elif [ "$(playerctl --player=playerctld status)" = "Paused"  ]; then
    polybar-msg -p "$(pgrep -f "polybar example")" hook spotify-play-pause 2 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
else # Can be configured to output differently when player is paused
    polybar-msg -p "$(pgrep -f "polybar example")" hook spotify-play-pause 1 >/dev/null
    playerctl --player=playerctld metadata --format "{{ title }} - {{ artist }}"
fi
`
scroll_spotify_status.sh : 

`#!/bin/bash

# see man zscroll for documentation of the following parameters
zscroll -l 30 \
        --delay 0.1 \
        --match-command "playerctl --player=playerctld status" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true '/home/prayag_s/.config/polybar/scripts/get_spotify_status.sh' &

wait
`
Any help will be greatly appreciated !

**Comment by KivalM** [comment]
Follow the instructions and use the modified version of the scripts mentioned a few messages above and it should work fine. At least that's what worked for me. Good luck!

**Comment by Morantoine** [comment]
My mistake was only a problem of permissions ! Sorry !
Thanks for the script and your help

**Comment by PrayagS** [comment]
Glad it worked for you! I'm closing the issue then. Feel free to discuss any further issues or enhancements.
